experiment_name: plus_mp20_lattice_eps_em_facit_eval

sampling:
  checkpoint_path: https://wandb.ai/xanderbaatz-danmarks-tekniske-universitet-dtu/mp20_lattice_eps_em/artifacts/model/mp20_lattice_eps_em_validation/v91/files/epoch_8900.pt
  method: em
  sampling_algorithm: 3
  n_steps: 300
  t_start: 1.0
  t_final: 1.0e-3
  n_samples: 1

dataset:
  task: csp
  name: mp20
  lattice_representation: kldm
  root: null
  batch_size: 16
  num_workers: 0
  pin_memory: false

model:
  eps: 1.0e-6
  lambda_l: 2.0
  lattice_parameterization: eps
  lattice_diffusion_type: VP
  wrapped_normal_K: 3
  tdm_n_sigmas: 2000
  tdm_compute_sigma_norm: true
  tdm_velocity_scale: 0.15915494309189535
  tdm_sigma_norm_estimator: quadrature
  tdm_sigma_norm_density_K: 40
  tdm_sigma_norm_grid_points: 8193
  tdm_sigma_norm_mc_samples: 20000
  score_network:
    hidden_dim: 512
    time_dim: 256
    num_layers: 6
    num_freqs: 128
    ln: true
    h_dim: 100
    smooth: false
    pred_v: true
    pred_l: true
    pred_h: false
    zero_cog: true

sampling_eval:
  evaluation: true
  split: test
  batch_size: 8
  num_targets: 7236
  subset_seed: 123
  validity_cutoff: 0.5
  n_seeds: 20
  from_seed: 0
  wandb_project: mp_20_sampling
  wandb_run_name: EVAL_plus_mp20_lattice_eps_em_facit
  wandb_resume_id: null
  progress_dir: ../../../artifacts/HPC/sampling_eval
